/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class Ventana extends javax.swing.JFrame {
    ArrayList<Ficha> fichas;
    String[] colores = {"Amarillo", "Rojo", "Azul", "Negro"};
    String fichax = null;
    String fichay = null;
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        fichas = new ArrayList<Ficha>();
        initComponents();
        crearFichas();
        pnlPrincipal.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                colocarFicha(fichax, fichay);
                System.out.println(fichax);
                System.out.println(fichay);
                
            }
        });
    }
    
    public void crearFichas(){
        String path = "C:\\Users\\User\\Documents\\Universidad\\II Semestre 2023\\"
                + "Introclases23II\\Proyecto2\\src\\main\\java\\com\\mycompany\\proyecto2\\img\\";
        int contador = 0;
        for (String color : colores) {
            for (int i = 1; i <= 13; i++) {
                JLabel label = new JLabel(Integer.toString(i) + color);
                label.setName(Integer.toString(i) + color);
                fichas.add(new Ficha(i, color, label));
                fichas.add(new Ficha(i, color, label));
                if (color.equals("Amarillo")){
                    label.setIcon(new ImageIcon(path + Integer.toString(i) + "amarillo.png"));
                } else if(color.equals("Rojo")){
                    label.setIcon(new ImageIcon(path + Integer.toString(i) + "rojo.png"));
                } else if(color.equals("Azul")){
                    label.setIcon(new ImageIcon(path + Integer.toString(i) + "azul.png"));
                } else if(color.equals("Negro")){
                    label.setIcon(new ImageIcon(path + Integer.toString(i) + "negro.png"));
                }
                pnlPrincipal.add(label);
                label.setSize(50, 50); 
                label.setLocation(i*50,contador*50);
               
                label.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        fichax = label.getText();
                    }
                });
                
            }
            contador += 1;
        
        }
        JLabel casilla2 = new JLabel("1rojovacio");
        casilla2.setIcon(new ImageIcon(path + "casilla.png"));
        pnlPrincipal.add(casilla2);
        casilla2.setSize(50,50);
        casilla2.setLocation(300,600);
        casilla2.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        fichay = casilla2.getText();
                    }
                });
        
        for (int i = 1; i < 10; i++) {
            JLabel casilla = new JLabel("casillaVacia");
            casilla.setIcon(new ImageIcon(path + "casilla.png"));
            pnlPrincipal.add(casilla);
            casilla.setSize(50,50);
            casilla.setLocation((i*50)+300,600);
            casilla.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        fichay = casilla.getText();
                    }
                });
        }
        
       
        
        for (Ficha ficha :fichas){
            System.out.println(ficha);
        }
    }
    
    public void colocarFicha(String fichax, String fichay){
        String path = "C:\\Users\\User\\Documents\\Universidad\\II Semestre 2023\\"
                + "Introclases23II\\Proyecto2\\src\\main\\java\\com\\mycompany\\proyecto2\\img\\";
        if(fichay.equals("1rojovacio") && (fichax.equals("1rojo"))){
            JLabel label = new JLabel("1rojo");
            label.setIcon(new ImageIcon(path + "1rojo.png"));
            pnlPrincipal.add(label);
            pnlPrincipal.setComponentZOrder(label, 0);
            label.setSize(50,50);
            label.setLocation(300,600);
        }
        else{
            System.out.println("Esa casilla no va ahi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(32, 65, 116));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(892, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(745, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 532, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String path = "C:\\Users\\User\\Documents\\Universidad\\II Semestre 2023\\"
                + "Introclases23II\\Proyecto2\\src\\main\\java\\com\\mycompany\\proyecto2\\img\\";
        
        JLabel label = new JLabel("1rojo");
        label.setIcon(new ImageIcon(path + "1rojo.png"));
        pnlPrincipal.add(label);
        pnlPrincipal.setComponentZOrder(label, 0);
        label.setSize(50,50);
        label.setLocation(300,600);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
